In [1]:
#importing important libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#data loading
game_data = pd.read_csv("games.csv")
sales_data = pd.read_csv("vgsales.csv")

Game_data

In [3]:
game_data.head()

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.6K,4.8K
1,1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21K,3.2K,6.3K,3.6K
2,2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30K,2.5K,5K,2.6K
3,3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28K,679,4.9K,1.8K
4,4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21K,2.4K,8.3K,2.3K

In [4]:
game_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1512 entries, 0 to 1511
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         1512 non-null   int64
 1   Title              1512 non-null   object
 2   Release Date       1512 non-null   object
 3   Team               1511 non-null   object
 4   Rating             1499 non-null   float64
 5   Times Listed       1512 non-null   object
 6   Number of Reviews  1512 non-null   object
 7   Genres             1512 non-null   object
 8   Summary            1511 non-null   object
 9   Reviews            1512 non-null   object
 10  Plays              1512 non-null   object
 11  Playing            1512 non-null   object
 12  Backlogs           1512 non-null   object
 13  Wishlist           1512 non-null   object
dtypes: float64(1), int64(1), object(12)
memory usage: 165.5+ KB

In [5]:
game_data.isnull().sum()

Unnamed: 0            0
Title                 0
Release Date          0
Team                  1
Rating               13
Times Listed          0
Number of Reviews     0
Genres                0
Summary               1
Reviews               0
Plays                 0
Playing               0
Backlogs              0
Wishlist              0
dtype: int64

Remove Unwanted Column

In [6]:
if 'Unnamed: 0' in game_data.columns:
    game_data.drop(columns=['Unnamed: 0'], inplace=True)

In [7]:
# Handling missing values 
game_data['Team'] = game_data['Team'].fillna('Unknown')
game_data['Summary'] = game_data['Summary'].fillna('No summary available')
game_data['Rating'] = game_data['Rating'].fillna(game_data['Rating'].mean())

In [8]:
# Convert release date to datetime format
game_data['Release Date'] = pd.to_datetime(game_data['Release Date'], errors='coerce')
game_data = game_data.dropna(subset=['Release Date'])

In [9]:
game_data.duplicated().sum()
game_data.drop_duplicates(inplace=True)

In [10]:
def clean_title(title):
    return title.lower().replace("-","").replace("(","").replace(")","").replace(":","").replace("&","").replace(",","").replace("[","").replace("]","").replace("'","").replace("'","").replace(" " ","").replace(" " ","")

In [11]:
# Data Cleaning
game_data['Title'] = game_data['Title'].astype(str).apply(clean_title)
game_data['Team'] = game_data['Team'].astype(str).apply(clean_title)
game_data['Genres'] = game_data['Genres'].astype(str).apply(clean_title)
game_data['Summary'] = game_data['Summary'].astype(str).apply(clean_title)
game_data['Reviews'] = game_data['Reviews'].astype(str).apply(clean_title)
game_data['Rating'] = game_data['Rating'].astype(str).apply(clean_title)
game_data['Playing'] = game_data['Playing'].astype(str).apply(clean_title)

In [12]:
# list of column that having 'k' value
k_col = ['Times Listed', 'Number of Reviews', 'Plays', 'Playing', 'Backlogs', 'Wishlist']

# converting 'k' value to numeric
for col in k_col:
    if col in game_data.columns:
        game_data[col] = game_data[col].astype(str).str.upper()
        game_data[col] = game_data[col].apply(lambda x: float(x.replace('K', '')) * 1000 if 'K' in x else x)
        game_data[col] = pd.to_numeric(game_data[col], errors='coerce')

In [13]:
game_data.isnull().sum()

Title                0
Release Date         0
Team                 0
Rating               0
Times Listed         0
Number of Reviews    0
Genres               0
Summary              0
Reviews              0
Plays                0
Playing              0
Backlogs             0
Wishlist             0
dtype: int64

In [14]:
game_data.to_csv('Clean_game_data.csv', index=False)

Sales_data

In [15]:
sales_data.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [16]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [17]:
sales_data.isnull().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [18]:
sales_data['Publisher'] = sales_data['Publisher'].fillna('Unknown')
sales_data['Year'] = sales_data['Year'].fillna(sales_data['Year'].median())

In [19]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16598 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16598 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [20]:
sales_data.duplicated().sum()

np.int64(0)

In [21]:
# Data Cleaning
sales_data['Name'] = sales_data['Name'].astype(str).apply(clean_title)

In [22]:
sales_data.to_csv('Clean_sales_data.csv', index=False)

In [23]:
sales_data.isna().sum()

Rank            0
Name            0
Platform        0
Year            0
Genre           0
Publisher       0
NA_Sales        0
EU_Sales        0
JP_Sales        0
Other_Sales     0
Global_Sales    0
dtype: int64

Merge Data

In [24]:
merged_data = pd.merge(game_data, sales_data, how='inner', left_on='Title', right_on='Name')

In [25]:
merged_data.head()

,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,...,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,minecraft,2011-11-18,mojang studios,4.3,2300.0,2300.0,adventure simulator,minecraft focuses on allowing the player to ex...,minecraft is what you make of it. unfortunatel...,33000.0,...,minecraft,X360,2013.0,Misc,Microsoft Game Studios,5.58,2.83,0.02,0.77,9.20
1,minecraft,2011-11-18,mojang studios,4.3,2300.0,2300.0,adventure simulator,minecraft focuses on allowing the player to ex...,minecraft is what you make of it. unfortunatel...,33000.0,...,minecraft,PS3,2014.0,Misc,Sony Computer Entertainment,1.97,2.51,0.00,0.94,5.42
2,minecraft,2011-11-18,mojang studios,4.3,2300.0,2300.0,adventure simulator,minecraft focuses on allowing the player to ex...,minecraft is what you make of it. unfortunatel...,33000.0,...,minecraft,PS4,2014.0,Misc,Sony Computer Entertainment Europe,1.38,1.87,0.12,0.65,4.02
3,minecraft,2011-11-18,mojang studios,4.3,2300.0,2300.0,adventure simulator,minecraft focuses on allowing the player to ex...,minecraft is what you make of it. unfortunatel...,33000.0,...,minecraft,XOne,2014.0,Misc,Microsoft Game Studios,1.43,0.76,0.00,0.22,2.41
4,minecraft,2011-11-18,mojang studios,4.3,2300.0,2300.0,adventure simulator,minecraft focuses on allowing the player to ex...,minecraft is what you make of it. unfortunatel...,33000.0,...,minecraft,PSV,2014.0,Misc,Sony Computer Entertainment Europe,0.28,0.79,0.87,0.32,2.25

In [26]:
merged_data.isnull().sum()

Title                0
Release Date         0
Team                 0
Rating               0
Times Listed         0
Number of Reviews    0
Genres               0
Summary              0
Reviews              0
Plays                0
Playing              0
Backlogs             0
Wishlist             0
Rank                 0
Name                 0
Platform             0
Year                 0
Genre                0
Publisher            0
NA_Sales             0
EU_Sales             0
JP_Sales             0
Other_Sales          0
Global_Sales         0
dtype: int64

In [27]:
merged_data.duplicated().sum()

np.int64(0)

In [28]:
merged_data = merged_data.drop(columns=['Name'])

In [29]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1065 entries, 0 to 1064
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              1065 non-null   object
 1   Release Date       1065 non-null   datetime64[ns]
 2   Team               1065 non-null   object
 3   Rating             1065 non-null   object
 4   Times Listed       1065 non-null   float64
 5   Number of Reviews  1065 non-null   float64
 6   Genres             1065 non-null   object
 7   Summary            1065 non-null   object
 8   Reviews            1065 non-null   object
 9   Plays              1065 non-null   float64
 10  Playing            1065 non-null   float64
 11  Backlogs           1065 non-null   float64
 12  Wishlist           1065 non-null   float64
 13  Rank               1065 non-null   int64
 14  Platform           1065 non-null   object
 15  Year               1065 non-null   float64
 16  Genre              1065 non-null   object
 17  Publisher          1065 non-null   object
 18  NA_Sales           1065 non-null   float64
 19  EU_Sales           1065 non-null   float64
 20  JP_Sales           1065 non-null   float64
 21  Other_Sales        1065 non-null   float64
 22  Global_Sales       1065 non-null   float64
dtypes: datetime64[ns](1), float64(12), int64(1), object(9)
memory usage: 191.5+ KB

In [30]:
merged_data.to_csv('merged_data.csv', index=False)

In [31]:
df = pd.read_csv("merged_data.csv")

In [32]:
df.head(3)

,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,...,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,minecraft,2011-11-18,mojang studios,4.3,2300.0,2300.0,adventure simulator,minecraft focuses on allowing the player to ex...,minecraft is what you make of it. unfortunatel...,33000.0,...,73,X360,2013.0,Misc,Microsoft Game Studios,5.58,2.83,0.02,0.77,9.20
1,minecraft,2011-11-18,mojang studios,4.3,2300.0,2300.0,adventure simulator,minecraft focuses on allowing the player to ex...,minecraft is what you make of it. unfortunatel...,33000.0,...,169,PS3,2014.0,Misc,Sony Computer Entertainment,1.97,2.51,0.00,0.94,5.42
2,minecraft,2011-11-18,mojang studios,4.3,2300.0,2300.0,adventure simulator,minecraft focuses on allowing the player to ex...,minecraft is what you make of it. unfortunatel...,33000.0,...,298,PS4,2014.0,Misc,Sony Computer Entertainment Europe,1.38,1.87,0.12,0.65,4.02

SQL Database Setup

In [33]:
#importing my sql connector
import mysql.connector

In [41]:
# My sql connection setup.

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Tigerx@007",

)
cursor = conn.cursor()

In [35]:
cursor.execute("CREATE DATABASE IF NOT EXISTS Video_game_sales_data")
print("MySQL database 'Video_game_sales_data' created successfully")

MySQL database 'Video_game_sales_data' created successfully

In [43]:
cursor.execute("use Video_game_sales_data")

In [44]:
# Get all table names and delete them
cursor.execute("SHOW TABLES")
tables = cursor.fetchall()

for table in tables:
    table_name = table[0]
    cursor.execute(f"DROP TABLE IF EXISTS {table_name}")
    print(f"Table {table_name} deleted successfully")

conn.commit()

Table game_data deleted successfully
Table merged_data deleted successfully
Table vgsales deleted successfully

In [45]:

# ==========  CREATE TABLES ==========
cursor.execute("""
    CREATE TABLE Game_data (
        Game_id INT PRIMARY KEY AUTO_INCREMENT,
        Title VARCHAR(500),
        Release_Date VARCHAR(50),
        Team TEXT,
        Rating FLOAT,
        Times_Listed FLOAT,
        Number_of_Reviews FLOAT,
        Genres VARCHAR(500),
        Summary TEXT,
        Reviews TEXT,
        Playing FLOAT,
        Plays FLOAT,
        Backlogs FLOAT,
        Wishlist FLOAT
    )
""")

cursor.execute("""
    CREATE TABLE VGSALES (
        Sales_id INT PRIMARY KEY AUTO_INCREMENT,
        Name VARCHAR(255), 
        Platform VARCHAR(255),
        Year VARCHAR(10),
        Genre VARCHAR(500),
        Publisher VARCHAR(500),
        NA_Sales FLOAT,
        EU_Sales FLOAT,
        JP_Sales FLOAT,
        Other_Sales FLOAT,
        Global_Sales FLOAT
    )
""")

cursor.execute("""
    CREATE TABLE merged_data (
        Title VARCHAR(500),
        Release_Date DATE,
        Team TEXT,
        Rating FLOAT,
        Times_Listed FLOAT,
        Number_of_Reviews FLOAT,
        Genres VARCHAR(500),
        Summary TEXT,
        Reviews TEXT,
        Playing FLOAT,
        Plays FLOAT,
        Backlogs FLOAT,
        Wishlist FLOAT, 
        Platform VARCHAR(255),
        Year VARCHAR(10),
        Genre VARCHAR(500),
        Publisher VARCHAR(500),
        NA_Sales FLOAT,
        EU_Sales FLOAT,
        JP_Sales FLOAT,
        Other_Sales FLOAT,
        Global_Sales FLOAT
    )
""")

print("✅ Tables created!")

✅ Tables created!

In [46]:
# ==========  Load Datasets ==========
game_data = pd.read_csv("Clean_game_data.csv")
sales_data = pd.read_csv("Clean_sales_data.csv")
merged_data = pd.read_csv("merged_data.csv")


# ==========  INSERT GAME_DATA ==========
print("Inserting Game_data...")
for index, row in game_data.iterrows():
    cursor.execute("""
        INSERT INTO Game_data (Title, Release_Date, Team, Rating, Times_Listed, 
                               Number_of_Reviews, Genres, Summary, Reviews, 
                               Playing, Plays, Backlogs, Wishlist)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """, (
        row['Title'], row['Release Date'], str(row['Team']), row['Rating'],
        row['Times Listed'], row['Number of Reviews'], str(row['Genres']),
        str(row['Summary']), str(row['Reviews']), 
        row['Playing'], row['Plays'], row['Backlogs'], row['Wishlist']
    ))

# ==========  INSERT VGSALES ==========
print("Inserting VGSALES...")
for index, row in sales_data.iterrows():
    cursor.execute("""
        INSERT INTO VGSALES (Name, Platform, Year, Genre, Publisher, 
                             NA_Sales, EU_Sales, JP_Sales, Other_Sales, Global_Sales)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """, (
        row['Name'], row['Platform'], str(row['Year']), row['Genre'], row['Publisher'],
        row['NA_Sales'], row['EU_Sales'], row['JP_Sales'], 
        row['Other_Sales'], row['Global_Sales']
    ))

# ==========  INSERT MERGED_DATA ==========
print("Inserting Merged_data...")
for index, row in merged_data.iterrows():
    cursor.execute("""
        INSERT INTO merged_data (Title, Release_Date, Team, Rating, Times_Listed, 
                                 Number_of_Reviews, Genres, Summary, Reviews, 
                                 Playing, Plays, Backlogs, Wishlist, Platform, Year,
                                 Genre, Publisher, NA_Sales, EU_Sales, JP_Sales,
                                 Other_Sales, Global_Sales)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """, (
        row['Title'], row['Release Date'], str(row['Team']), row['Rating'], row['Times Listed'],
        row['Number of Reviews'], str(row['Genres']), str(row['Summary']), str(row['Reviews']),
        row['Playing'], row['Plays'], row['Backlogs'], row['Wishlist'], 
        row['Platform'], row['Year'], row['Genre'], row['Publisher'],
        row['NA_Sales'], row['EU_Sales'], row['JP_Sales'], row['Other_Sales'], row['Global_Sales']
    ))

# ========== 7. COMMIT ==========
conn.commit()
print("✅ All data inserted successfully!")

cursor.close()
conn.close()

Inserting Game_data...
Inserting VGSALES...
Inserting Merged_data...
✅ All data inserted successfully!